### ISSUE TITLE
[Bug] Labels and annotations result in a broken template

### ISSUE THREAD

**Issue by aclevername** [syntasso/kratix-backstage-generator-pipeline#1]
Given the following Promise with the generator pipeline adeed : https://github.com/syntasso/kratix-marketplace/blob/main/mongodb/full/promise.yaml

It produces a UI that cannot be walked through, pressing `Next Steps` does nothing:
![Screenshot 2024-01-05 at 16 58 06](https://github.com/syntasso/kratix-backstage-generator-pipeline/assets/19669095/92b23af2-5567-4ae9-ae67-0c67e0d29c5b)

snippet of CRD thats of interest to debug:
```
                  statefulSet:
                    description: StatefulSetConfiguration holds the optional custom
                      StatefulSet that should be merged into the operator created
                      one.
                    properties:
                      metadata:
                        description: StatefulSetMetadataWrapper is a wrapper around
                          Labels and Annotations
                        properties:
                          annotations:
                            additionalProperties:
                              type: string
                            type: object
                          labels:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                      spec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - spec
                    type: object
```

I think `spec` is required, but cannot be filled in since it contains no declared fields.
